# Generated by Django 5.2.3 on 2025-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
        migrations.AddField(
            model_name="room",
            name="total_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("budget", "Budget Room"), ("superior", "Superior Room")],
                default="budget",
                max_length=20,
            ),
        ),
    ]
