# Generated by Django 5.2.3 on 2025-06-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_contactmessage_full_name_roomimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price_per_night", models.PositiveIntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_prices",
                        to="core.room",
                    ),
                ),
            ],
        ),
    ]
